#!/usr/bin/env python3
"""Generate paper/tables/phase3_attacks_synthetic.{csv,md} from
experiments/phase3_synthetic/*.json. Never hand-typed. Re-run after any
config/code change.

Usage: PYTHONPATH=. python scripts/make_phase3_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase3_synthetic")
OUT_CSV = Path("paper/tables/phase3_attacks_synthetic.csv")
OUT_MD = Path("paper/tables/phase3_attacks_synthetic.md")


def mean_std(vals):
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("seed*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase3_synthetic.py first")

    rows = []

    dlg_psnr = [r["gradient_inversion"]["psnr_db"] for r in runs]
    dlg_mse = [r["gradient_inversion"]["mse"] for r in runs]
    m, s = mean_std(dlg_psnr)
    rows.append({"attack": "gradient_inversion (DLG, single unaggregated gradient)", "n_seeds": len(runs),
                 "metric": "PSNR_dB", "mean": m, "std": s, "note": f"mse mean={statistics.mean(dlg_mse):.4f}"})

    mi_auc = [r["membership_inference"]["attack_auc"] for r in runs]
    m, s = mean_std(mi_auc)
    rows.append({"attack": "membership_inference (loss-threshold)", "n_seeds": len(runs),
                 "metric": "attack_AUC", "mean": m, "std": s,
                 "note": f"pre-registered target <= 0.55 (docs/research_scope.md)"})

    for i, budget in enumerate(runs[0]["adapter_reconstruction"]):
        vals = [r["adapter_reconstruction"][i]["u_attack_fine_macro_f1"] for r in runs]
        m, s = mean_std(vals)
        rows.append({"attack": "adapter_reconstruction (A2)", "n_seeds": len(runs),
                     "metric": f"fine_macro_f1 @ {budget['compute_budget']}", "mean": m, "std": s, "note": ""})

    for i, budget in enumerate(runs[0]["extraction"]):
        vals = [r["extraction"][i]["u_attack_fine_macro_f1"] for r in runs]
        m, s = mean_std(vals)
        rows.append({"attack": "black_box_extraction (A3)", "n_seeds": len(runs),
                     "metric": f"fine_macro_f1 @ {budget['compute_budget']}", "mean": m, "std": s, "note": ""})

    col_gain = [r["collusion"]["collusion_gain_over_solo"] for r in runs]
    m, s = mean_std(col_gain)
    rows.append({"attack": "collusion (2 attackers vs solo, same total budget)", "n_seeds": len(runs),
                 "metric": "fine_macro_f1 gain over solo", "mean": m, "std": s, "note": ""})

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 3 security attacks — SYNTHETIC TIER (pipeline validation, not a scientific result)",
        "",
        "Real Fed-ISIC2019 results are BLOCKED-LICENSE; see docs/execution_plan.md.",
        "Generated by scripts/make_phase3_table.py from experiments/phase3_synthetic/*.json — do not hand-edit.",
        "Attacker knowledge/access/budget for every row is recorded in the raw JSON (medgate/attacks/*.py docstrings + result dicts), not just here.",
        "",
        "| attack | n_seeds | metric | mean | std | note |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(f"| {row['attack']} | {row['n_seeds']} | {row['metric']} | {row['mean']:.3f} | {row['std']:.3f} | {row['note']} |")
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} seeds")


if __name__ == "__main__":
    main()
