#!/usr/bin/env python3
"""Generate paper/tables/phase1_hierarchical.{csv,md} from
experiments/phase1_hierarchical/*.json. Never hand-typed.

Usage: PYTHONPATH=. python scripts/make_phase1_hierarchical_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase1_hierarchical")
OUT_CSV = Path("paper/tables/phase1_hierarchical.csv")
OUT_MD = Path("paper/tables/phase1_hierarchical.md")


def mean_std(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None, 0
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0), len(vals)


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("seed*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase1_hierarchical.py first")

    groups = {}
    for run in runs:
        for r in run["results"]:
            groups.setdefault(r["method"], {"kind": r["kind"], "coarse_f1": [], "fine_f1": [], "u_public": [], "rfc": [], "ucg": [], "arr": []})
            g = groups[r["method"]]
            g["coarse_f1"].append(r["utility"]["coarse_macro_f1"])
            g["fine_f1"].append(r["utility"]["fine_macro_f1"])
            g["u_public"].append(r["u_public"])
            g["rfc"].append(r["residual_fine_capability"])
            g["ucg"].append(r["unauthorized_capability_gain"])
            g["arr"].append(r["authorized_recovery_ratio"])

    order = ["random_frozen_lora", "coarse_pretrained_fedlora", "imagenet_pretrained_fedlora", "full_finetune",
              "coarse_only", "hidden_fine_head", "adapter_isolation", "adversarial", "orthogonal", "combined"]
    rows = []
    for method in order:
        if method not in groups:
            continue
        g = groups[method]
        row = {"method": method, "kind": g["kind"], "n_seeds": len(g["coarse_f1"])}
        for key in ("coarse_f1", "fine_f1", "u_public", "rfc", "ucg", "arr"):
            m, s, n = mean_std(g[key])
            row[f"{key}_mean"] = m
            row[f"{key}_std"] = s
            row[f"{key}_n"] = n
        rows.append(row)

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    def fmt(m, s):
        return "n/a" if m is None else f"{m:.3f} ± {s:.3f}"

    lines = [
        "# Phase 1+2 fair-baseline repair — HIERARCHICAL-SIGNAL FIXTURE (real learnable signal, still synthetic)",
        "",
        "Generated by scripts/make_phase1_hierarchical_table.py from experiments/phase1_hierarchical/*.json — do not hand-edit.",
        "`random_frozen_lora` is a NEGATIVE SANITY CONTROL (backbone frozen at RANDOM init), never a fair FedLoRA baseline",
        "-- see medgate/federated/baselines.py. ARR values outside [0,1] (including negative and >1) occur when a method's",
        "own denominator (U_plain_adapter - U_public) is small -- reported as computed, not clipped, per the project's",
        "'never hide failure behind a composite score' rule; read alongside the raw fine macro-F1/u_public/RFC columns.",
        f"n_seeds = {len(runs)} (resource-constrained on CPU-only hardware, docs/hardware_report.md — see docs/execution_plan.md",
        "for the wall-clock cost that drove this).",
        "",
        "| method | kind | n_seeds | coarse macro-F1 | fine macro-F1 | U_public | RFC | UCG | ARR |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['method']} | {row['kind']} | {row['n_seeds']} "
            f"| {fmt(row['coarse_f1_mean'], row['coarse_f1_std'])} "
            f"| {fmt(row['fine_f1_mean'], row['fine_f1_std'])} "
            f"| {fmt(row['u_public_mean'], row['u_public_std'])} "
            f"| {fmt(row['rfc_mean'], row['rfc_std'])} "
            f"| {fmt(row['ucg_mean'], row['ucg_std'])} "
            f"| {fmt(row['arr_mean'], row['arr_std'])} |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} seeds, {len(rows)} methods")


if __name__ == "__main__":
    main()
