#!/usr/bin/env python3
"""Generate paper/tables/phase2_capability_isolation_synthetic.{csv,md}
from experiments/phase2_synthetic/*.json. Never hand-typed (reproducibility
requirement) — re-run after any config/code change.

Usage: PYTHONPATH=. python scripts/make_phase2_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase2_synthetic")
OUT_CSV = Path("paper/tables/phase2_capability_isolation_synthetic.csv")
OUT_MD = Path("paper/tables/phase2_capability_isolation_synthetic.md")


def load_runs():
    runs = []
    for path in sorted(IN_DIR.glob("*.json")):
        r = json.loads(path.read_text())
        runs.append({
            "method": r["method"],
            "seed": r["seed"],
            "fine_macro_f1": r["utility"]["fine_macro_f1"],
            "coarse_macro_f1": r["utility"]["coarse_macro_f1"],
            "u_public": r["u_public"],
            "rfc": r["residual_fine_capability"],
            "ucg": r["unauthorized_capability_gain"],
            "arr": r["authorized_recovery_ratio"],  # may be None
        })
    return runs


def mean_std(vals):
    vals = [v for v in vals if v is not None]
    if not vals:
        return None, None, 0
    m = statistics.mean(vals)
    s = statistics.stdev(vals) if len(vals) > 1 else 0.0
    return m, s, len(vals)


def aggregate(runs):
    methods = sorted({r["method"] for r in runs}, key=lambda m: (m != "adapter_isolation", m))
    agg = []
    for m in methods:
        rows = [r for r in runs if r["method"] == m]
        entry = {"method": m, "n_seeds": len(rows)}
        for k in ("fine_macro_f1", "coarse_macro_f1", "u_public", "rfc", "ucg", "arr"):
            mean, std, n = mean_std([r[k] for r in rows])
            entry[f"{k}_mean"] = mean
            entry[f"{k}_std"] = std
            entry[f"{k}_n"] = n
        agg.append(entry)
    return agg


def fmt(mean, std):
    return "n/a" if mean is None else f"{mean:.3f} ± {std:.3f}"


def write_csv(agg):
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(agg[0].keys()))
        w.writeheader()
        w.writerows(agg)


def write_md(agg):
    lines = [
        "# Phase 2 capability isolation — SYNTHETIC TIER (pipeline validation, not a scientific result)",
        "",
        "Real Fed-ISIC2019 results are BLOCKED-LICENSE; see docs/execution_plan.md.",
        "Generated by scripts/make_phase2_table.py from experiments/phase2_synthetic/*.json — do not hand-edit.",
        "ARR is `n/a` when the plain-adapter/public denominator was ~0 for every seed (expected on synthetic data — see medgate/capability_metrics.py).",
        "",
        "| method | n_seeds | authorized fine macro-F1 | U_public (output-only probe) | RFC (best repr. probe) | UCG | ARR |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in agg:
        lines.append(
            f"| {row['method']} | {row['n_seeds']} "
            f"| {fmt(row['fine_macro_f1_mean'], row['fine_macro_f1_std'])} "
            f"| {fmt(row['u_public_mean'], row['u_public_std'])} "
            f"| {fmt(row['rfc_mean'], row['rfc_std'])} "
            f"| {fmt(row['ucg_mean'], row['ucg_std'])} "
            f"| {fmt(row['arr_mean'], row['arr_std'])} ({row['arr_n']}/{row['n_seeds']} seeds defined) |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")


def main():
    runs = load_runs()
    if not runs:
        raise SystemExit(f"no run JSON files found under {IN_DIR} — run scripts/run_phase2_synthetic.py first")
    agg = aggregate(runs)
    write_csv(agg)
    write_md(agg)
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} runs across {len(agg)} methods")


if __name__ == "__main__":
    main()
