#!/usr/bin/env python3
"""Generate paper/tables/phase5_unlearning_synthetic.{csv,md} from
experiments/phase5_synthetic/*.json. Never hand-typed. Re-run after any
config/code change.

Usage: PYTHONPATH=. python scripts/make_phase5_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase5_synthetic")
OUT_CSV = Path("paper/tables/phase5_unlearning_synthetic.csv")
OUT_MD = Path("paper/tables/phase5_unlearning_synthetic.md")


def mean_std(vals):
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase5_synthetic.py first")

    groups = {}
    for run in runs:
        for method, m in run["methods"].items():
            key = (run["scenario"], method)
            groups.setdefault(key, {"retained_f1": [], "gap": [], "forget_auc": []})
            groups[key]["retained_f1"].append(m["retained_fine_macro_f1"])
            groups[key]["gap"].append(m["gap_to_gold_standard"])
            groups[key]["forget_auc"].append(m["forgetting_auc"])

    rows = []
    for (scenario, method), vals in sorted(groups.items()):
        f1_m, f1_s = mean_std(vals["retained_f1"])
        gap_m, gap_s = mean_std(vals["gap"])
        auc_m, auc_s = mean_std(vals["forget_auc"])
        rows.append({
            "scenario": scenario, "method": method, "n_seeds": len(vals["retained_f1"]),
            "retained_fine_macro_f1_mean": f1_m, "retained_fine_macro_f1_std": f1_s,
            "gap_to_gold_standard_mean": gap_m, "gap_to_gold_standard_std": gap_s,
            "forgetting_auc_mean": auc_m, "forgetting_auc_std": auc_s,
        })

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 5 revocation and unlearning — SYNTHETIC TIER (pipeline validation, not a scientific result)",
        "",
        "Real Fed-ISIC2019 results are BLOCKED-LICENSE; see docs/execution_plan.md.",
        "Generated by scripts/make_phase5_table.py from experiments/phase5_synthetic/*.json — do not hand-edit.",
        "forgetting_auc: membership-inference AUC between the removed data and held-out retained test data. ~0.5 = removed",
        "data no longer distinguishable from never-seen data (good forgetting); far from 0.5 = still distinguishable.",
        "CAUTION for the `class` scenario specifically: removed data and retained test data have DIFFERENT class",
        "composition by construction (one class vs. the other seven), so forgetting_auc there is confounded with any",
        "class-level asymmetry in typical loss that exists even in an UNTRAINED model -- see docs/execution_plan.md.",
        "The `institution` scenario does not have this confound (all institutions share the same label distribution).",
        "",
        "| scenario | method | n_seeds | retained fine macro-F1 | gap to gold standard | forgetting AUC |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['scenario']} | {row['method']} | {row['n_seeds']} "
            f"| {row['retained_fine_macro_f1_mean']:.3f} ± {row['retained_fine_macro_f1_std']:.3f} "
            f"| {row['gap_to_gold_standard_mean']:+.3f} ± {row['gap_to_gold_standard_std']:.3f} "
            f"| {row['forgetting_auc_mean']:.3f} ± {row['forgetting_auc_std']:.3f} |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} run files, {len(rows)} scenario/method combinations")


if __name__ == "__main__":
    main()
