#!/usr/bin/env python3
"""Generate paper/tables/phase4_privacy_synthetic.{csv,md} (the
privacy-utility Pareto data) from experiments/phase4_synthetic/*.json.
Never hand-typed. Re-run after any config/code change.

Usage: PYTHONPATH=. python scripts/make_phase4_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase4_synthetic")
OUT_CSV = Path("paper/tables/phase4_privacy_synthetic.csv")
OUT_MD = Path("paper/tables/phase4_privacy_synthetic.md")


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("seed*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase4_synthetic.py first")

    # group by (arm, noise_multiplier) across seeds
    groups = {}
    for run in runs:
        for arm in run["arms"]:
            key = (arm["arm"], arm["noise_multiplier"])
            groups.setdefault(key, {"fine_f1": [], "coarse_f1": [], "epsilon": []})
            groups[key]["fine_f1"].append(arm["utility"]["fine_macro_f1"])
            groups[key]["coarse_f1"].append(arm["utility"]["coarse_macro_f1"])
            if arm["epsilon"] is not None:
                groups[key]["epsilon"].append(arm["epsilon"])

    rows = []
    for (arm, nm), vals in sorted(groups.items(), key=lambda kv: (kv[0][0], kv[0][1] or 0)):
        f1_mean = statistics.mean(vals["fine_f1"])
        f1_std = statistics.stdev(vals["fine_f1"]) if len(vals["fine_f1"]) > 1 else 0.0
        eps = vals["epsilon"][0] if vals["epsilon"] else None
        rows.append({
            "arm": arm, "noise_multiplier": nm, "epsilon": eps,
            "fine_macro_f1_mean": f1_mean, "fine_macro_f1_std": f1_std, "n_seeds": len(vals["fine_f1"]),
        })

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 4 privacy-utility Pareto — SYNTHETIC TIER (pipeline validation, not a scientific result)",
        "",
        "Real Fed-ISIC2019 results are BLOCKED-LICENSE; see docs/execution_plan.md.",
        "Generated by scripts/make_phase4_table.py from experiments/phase4_synthetic/*.json — do not hand-edit.",
        "no_protection/secure_agg have epsilon=n/a (no DP noise); dp_sgd/secure_agg_plus_dp show epsilon at delta=1e-5.",
        "Note: dp_sgd and secure_agg_plus_dp show IDENTICAL utility at every noise multiplier -- this is the correct,",
        "expected behavior (secure-aggregation masking cancels exactly in the sum, so it changes what the server can",
        "OBSERVE per-client, never the final aggregated model) -- not a bug and not evidence the two arms are redundant.",
        "",
        "| arm | noise_multiplier | epsilon (delta=1e-5) | fine macro-F1 | n_seeds |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        eps_str = f"{row['epsilon']:.2f}" if row["epsilon"] is not None else "n/a"
        nm_str = row["noise_multiplier"] if row["noise_multiplier"] is not None else "n/a"
        lines.append(
            f"| {row['arm']} | {nm_str} | {eps_str} "
            f"| {row['fine_macro_f1_mean']:.3f} ± {row['fine_macro_f1_std']:.3f} | {row['n_seeds']} |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} seeds, {len(rows)} arm/budget combinations")


if __name__ == "__main__":
    main()
