#!/usr/bin/env python3
"""Generate paper/tables/phase5_hierarchical_unlearning.{csv,md} from
experiments/phase5_hierarchical_unlearning/*.json (P1 requirement #5,
repair pass 4). Never hand-typed.

Usage: PYTHONPATH=. python scripts/make_phase5_hierarchical_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase5_hierarchical_unlearning")
TABLES = Path("paper/tables")


def mean_std(vals):
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("*_seed*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase5_hierarchical_unlearning.py first")

    groups = {}
    for run in runs:
        scenario = run["scenario"]
        for method, m in run["methods"].items():
            key = (scenario, method)
            groups.setdefault(key, {"retained_f1": [], "gap": [], "sym_auc": [], "advantage": []})
            groups[key]["retained_f1"].append(m["retained_fine_macro_f1"])
            groups[key]["gap"].append(m["gap_to_gold_standard"])
            groups[key]["sym_auc"].append(m["forgetting_symmetric_auc"])
            groups[key]["advantage"].append(m["forgetting_attack_advantage"])

    method_order = ["full_retrain", "checkpoint_rollback", "adapter_deletion_and_retrain", "gradient_ascent_unlearning", "key_revocation_only"]
    rows = []
    for scenario in ("patient", "patient_group"):
        for method in method_order:
            key = (scenario, method)
            if key not in groups:
                continue
            g = groups[key]
            rf_m, rf_s = mean_std(g["retained_f1"])
            gap_m, gap_s = mean_std(g["gap"])
            auc_m, auc_s = mean_std(g["sym_auc"])
            adv_m, adv_s = mean_std(g["advantage"])
            rows.append({
                "scenario": scenario, "method": method, "n_seeds": len(g["retained_f1"]),
                "retained_fine_macro_f1_mean": rf_m, "retained_fine_macro_f1_std": rf_s,
                "gap_to_gold_standard_mean": gap_m, "gap_to_gold_standard_std": gap_s,
                "forgetting_symmetric_auc_mean": auc_m, "forgetting_symmetric_auc_std": auc_s,
                "forgetting_attack_advantage_mean": adv_m, "forgetting_attack_advantage_std": adv_s,
            })

    out_csv = TABLES / "phase5_hierarchical_unlearning.csv"
    with open(out_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 5 P1 patient-level / patient-group unlearning — HIERARCHICAL FIXTURE",
        "", "Generated by scripts/make_phase5_hierarchical_table.py -- do not hand-edit.",
        "patient removes 1 patient (3 examples); patient_group removes 3 patients (9 examples), one institution.",
        "full_retrain's own forgetting_symmetric_auc (never trained on the removed data at all) is a direct",
        "small-sample-noise check: patient (n=3 removed) reads 0.56-0.96 across seeds (noisy, not a confound --",
        "compare patient_group's n=9, which reads a tighter 0.52-0.63), read patient-scenario numbers with that caveat.",
        "", "| scenario | method | seeds | retained fine-F1 | gap to gold | SymmetricAUC | attack advantage |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['scenario']} | {row['method']} | {row['n_seeds']} "
            f"| {row['retained_fine_macro_f1_mean']:.3f} ± {row['retained_fine_macro_f1_std']:.3f} "
            f"| {row['gap_to_gold_standard_mean']:+.3f} ± {row['gap_to_gold_standard_std']:.3f} "
            f"| {row['forgetting_symmetric_auc_mean']:.3f} ± {row['forgetting_symmetric_auc_std']:.3f} "
            f"| {row['forgetting_attack_advantage_mean']:.3f} ± {row['forgetting_attack_advantage_std']:.3f} |"
        )
    (TABLES / "phase5_hierarchical_unlearning.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {out_csv} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
