#!/usr/bin/env python3
"""Generate paper/tables/phase1_utility_synthetic.{csv,md} from the raw
per-run JSON files under experiments/phase1_synthetic/. Never hand-type
these numbers into the paper (reproducibility requirement) — re-run this
script after any change to configs/phase1_synthetic.yaml or the code.

Usage: PYTHONPATH=. python scripts/make_phase1_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase1_synthetic")
OUT_CSV = Path("paper/tables/phase1_utility_synthetic.csv")
OUT_MD = Path("paper/tables/phase1_utility_synthetic.md")

METRIC_KEYS = [
    "coarse_macro_f1", "coarse_balanced_accuracy",
    "fine_macro_f1", "fine_balanced_accuracy",
    "worst_institution_fine_macro_f1",
]


def load_runs():
    runs = []
    for path in sorted(IN_DIR.glob("*.json")):
        r = json.loads(path.read_text())
        row = {"baseline": r["baseline"], "seed": r["seed"], "wall_clock_seconds": r["wall_clock_seconds"]}
        pooled = r["metrics"]["pooled"]
        for k in METRIC_KEYS:
            row[k] = pooled[k] if k in pooled else r["metrics"][k]
        runs.append(row)
    return runs


def aggregate(runs):
    baselines = sorted({r["baseline"] for r in runs})
    agg = []
    for b in baselines:
        rows = [r for r in runs if r["baseline"] == b]
        entry = {"baseline": b, "n_seeds": len(rows)}
        for k in METRIC_KEYS + ["wall_clock_seconds"]:
            vals = [r[k] for r in rows]
            entry[f"{k}_mean"] = statistics.mean(vals)
            entry[f"{k}_std"] = statistics.stdev(vals) if len(vals) > 1 else 0.0
        agg.append(entry)
    return agg


def write_csv(agg):
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(agg[0].keys())
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for row in agg:
            w.writerow(row)


def write_md(agg):
    lines = [
        "# Phase 1 primary utility — SYNTHETIC TIER (pipeline validation, not a scientific result)",
        "",
        "Real Fed-ISIC2019 results are BLOCKED-LICENSE; see docs/execution_plan.md.",
        "Generated by scripts/make_phase1_table.py from experiments/phase1_synthetic/*.json — do not hand-edit.",
        "",
        "| baseline | n_seeds | coarse macro-F1 | fine macro-F1 | worst-institution fine macro-F1 | wall-clock (s) |",
        "|---|---|---|---|---|---|",
    ]
    for row in agg:
        lines.append(
            f"| {row['baseline']} | {row['n_seeds']} "
            f"| {row['coarse_macro_f1_mean']:.3f} ± {row['coarse_macro_f1_std']:.3f} "
            f"| {row['fine_macro_f1_mean']:.3f} ± {row['fine_macro_f1_std']:.3f} "
            f"| {row['worst_institution_fine_macro_f1_mean']:.3f} ± {row['worst_institution_fine_macro_f1_std']:.3f} "
            f"| {row['wall_clock_seconds_mean']:.1f} ± {row['wall_clock_seconds_std']:.1f} |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")


def main():
    runs = load_runs()
    if not runs:
        raise SystemExit(f"no run JSON files found under {IN_DIR} — run scripts/run_phase1_synthetic.py first")
    agg = aggregate(runs)
    write_csv(agg)
    write_md(agg)
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} runs across {len(agg)} baselines")


if __name__ == "__main__":
    main()
