#!/usr/bin/env python3
"""Generate paper/tables/phase3_integrity_synthetic.{csv,md} from
experiments/phase3_integrity_synthetic/*.json. Never hand-typed.

Usage: PYTHONPATH=. python scripts/make_phase3_integrity_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase3_integrity_synthetic")
OUT_CSV = Path("paper/tables/phase3_integrity_synthetic.csv")
OUT_MD = Path("paper/tables/phase3_integrity_synthetic.md")


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("seed*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase3_integrity_synthetic.py first")

    groups = {}
    for run in runs:
        for r in run["integrity_results"]:
            key = (r["attack"], r["aggregator"])
            groups.setdefault(key, {"fine_f1": [], "nan": [], "failed": 0, "backdoor_rate": []})
            if r.get("aggregation_failed"):
                groups[key]["failed"] += 1
                continue
            groups[key]["fine_f1"].append(r["fine_macro_f1"])
            groups[key]["nan"].append(r["model_has_nan"])
            if "backdoor_success_rate" in r and r["backdoor_success_rate"] is not None:
                groups[key]["backdoor_rate"].append(r["backdoor_success_rate"])

    pi_aucs = [r["property_inference"]["attack_auc"] for r in runs if r["property_inference"]["attack_auc"] is not None]

    rows = []
    for (attack, agg), vals in sorted(groups.items()):
        n = len(vals["fine_f1"])
        f1_mean = statistics.mean(vals["fine_f1"]) if n else float("nan")
        f1_std = statistics.stdev(vals["fine_f1"]) if n > 1 else 0.0
        nan_rate = sum(vals["nan"]) / n if n else float("nan")
        bd = statistics.mean(vals["backdoor_rate"]) if vals["backdoor_rate"] else None
        rows.append({
            "attack": attack, "aggregator": agg, "n_seeds": n, "n_aggregation_failures": vals["failed"],
            "fine_macro_f1_mean": f1_mean, "fine_macro_f1_std": f1_std,
            "model_corrupted_rate": nan_rate, "backdoor_success_rate_mean": bd,
        })

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 3 integrity attacks vs. aggregators — SYNTHETIC TIER (pipeline validation, not a scientific result)",
        "",
        "Generated by scripts/make_phase3_integrity_table.py from experiments/phase3_integrity_synthetic/*.json — do not hand-edit.",
        "model_corrupted_rate: fraction of seeds where the resulting global model contains NaN (a total, irrecoverable",
        "corruption from a single malformed update under plaintext FedAvg -- see the `malformed`/`fedavg` row).",
        "",
        "| attack | aggregator | seeds | fine macro-F1 | model corrupted rate | backdoor success rate |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        bd = "n/a" if row["backdoor_success_rate_mean"] is None else f"{row['backdoor_success_rate_mean']:.3f}"
        lines.append(
            f"| {row['attack']} | {row['aggregator']} | {row['n_seeds']} "
            f"| {row['fine_macro_f1_mean']:.3f} ± {row['fine_macro_f1_std']:.3f} "
            f"| {row['model_corrupted_rate']:.2f} | {bd} |"
        )
    lines.append("")
    if pi_aucs:
        lines.append(
            f"Property inference (leave-one-client-out, {len(pi_aucs)} seeds with a non-degenerate property split): "
            f"AUC mean {statistics.mean(pi_aucs):.3f}, std {(statistics.stdev(pi_aucs) if len(pi_aucs) > 1 else 0.0):.3f}. "
            "Read with caution: only 6 clients total, so a leave-one-out AUC estimate here has very high variance."
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} seeds, {len(rows)} attack/aggregator combinations")


if __name__ == "__main__":
    main()
