#!/usr/bin/env python3
"""Generate paper/tables/phase1_hierarchical_sensitivity.{csv,md} from
experiments/phase1_hierarchical_sensitivity/sensitivity.json (P1
requirement #6, repair pass 4). Never hand-typed.

Usage: PYTHONPATH=. python scripts/make_phase1_hierarchical_sensitivity_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_PATH = Path("experiments/phase1_hierarchical_sensitivity/sensitivity.json")
TABLES = Path("paper/tables")


def mean_std(vals):
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def main():
    if not IN_PATH.exists():
        raise SystemExit(f"{IN_PATH} not found — run scripts/run_phase1_hierarchical_sensitivity.py first")
    data = json.loads(IN_PATH.read_text())

    grouped = {}
    for row in data["rows"]:
        key = (row["dimension"], row["value"])
        grouped.setdefault(key, {"baseline_f1": [], "combined_f1": [], "baseline_rfc": [], "combined_rfc": []})
        grouped[key]["baseline_f1"].append(row["coarse_pretrained_fedlora"]["fine_macro_f1"])
        grouped[key]["combined_f1"].append(row["combined"]["fine_macro_f1"])
        grouped[key]["baseline_rfc"].append(row["coarse_pretrained_fedlora"]["rfc"])
        grouped[key]["combined_rfc"].append(row["combined"]["rfc"])

    rows = []
    for (dimension, value), g in grouped.items():
        bf_m, bf_s = mean_std(g["baseline_f1"])
        cf_m, cf_s = mean_std(g["combined_f1"])
        br_m, br_s = mean_std(g["baseline_rfc"])
        cr_m, cr_s = mean_std(g["combined_rfc"])
        rows.append({
            "dimension": dimension, "value": value, "n_seeds": len(g["combined_f1"]),
            "baseline_fine_f1_mean": bf_m, "baseline_fine_f1_std": bf_s,
            "combined_fine_f1_mean": cf_m, "combined_fine_f1_std": cf_s,
            "baseline_rfc_mean": br_m, "baseline_rfc_std": br_s,
            "combined_rfc_mean": cr_m, "combined_rfc_std": cr_s,
        })

    out_csv = TABLES / "phase1_hierarchical_sensitivity.csv"
    with open(out_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 1+2 P1 sensitivity sweep — HIERARCHICAL FIXTURE",
        "", "Generated by scripts/make_phase1_hierarchical_sensitivity_table.py -- do not hand-edit.",
        "2 seeds/point (sensitivity CHECK, not the main sweep's 5-seed statistical comparison).",
        "baseline = coarse_pretrained_fedlora; combined = the full proposed capability-isolation objective.",
        "", "| dimension | value | seeds | baseline fine-F1 | combined fine-F1 | baseline RFC | combined RFC |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['dimension']} | {row['value']} | {row['n_seeds']} "
            f"| {row['baseline_fine_f1_mean']:.3f} ± {row['baseline_fine_f1_std']:.3f} "
            f"| {row['combined_fine_f1_mean']:.3f} ± {row['combined_fine_f1_std']:.3f} "
            f"| {row['baseline_rfc_mean']:.3f} ± {row['baseline_rfc_std']:.3f} "
            f"| {row['combined_rfc_mean']:.3f} ± {row['combined_rfc_std']:.3f} |"
        )
    (TABLES / "phase1_hierarchical_sensitivity.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {out_csv} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
