#!/usr/bin/env python3
"""Generate paper/tables/phase3_adapter_recovery_synthetic.{csv,md} from
experiments/phase3_adapter_recovery_synthetic/*.json. Never hand-typed.

Usage: PYTHONPATH=. python scripts/make_phase3_adapter_recovery_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase3_adapter_recovery_synthetic")
OUT_CSV = Path("paper/tables/phase3_adapter_recovery_synthetic.csv")
OUT_MD = Path("paper/tables/phase3_adapter_recovery_synthetic.md")


def mean_std(vals):
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("seed*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase3_adapter_recovery_synthetic.py first")

    rows = []
    for i, budget in enumerate(runs[0]["solo"]):
        reveal = budget["compute_budget"]["reveal_fraction"]
        cos = [r["solo"][i]["parameter_space_recovery"]["cosine_similarity"] for r in runs]
        frob = [r["solo"][i]["parameter_space_recovery"]["normalized_frobenius_error"] for r in runs]
        func = [r["solo"][i]["functional_recovery_fine_macro_f1"] for r in runs]
        cm, cs = mean_std(cos)
        fm, fs = mean_std(frob)
        um, us = mean_std(func)
        rows.append({"scenario": "solo", "reveal_fraction": reveal, "n_seeds": len(runs),
                     "cosine_similarity_mean": cm, "cosine_similarity_std": cs,
                     "normalized_frobenius_error_mean": fm, "normalized_frobenius_error_std": fs,
                     "functional_fine_macro_f1_mean": um, "functional_fine_macro_f1_std": us})

    pooled_fracs = [r["collusion"]["compute_budget"]["pooled_reveal_fraction"] for r in runs]
    solo_cos = [r["collusion"]["solo_parameter_space_recovery"]["cosine_similarity"] for r in runs]
    coll_cos = [r["collusion"]["colluded_parameter_space_recovery"]["cosine_similarity"] for r in runs]
    solo_frob = [r["collusion"]["solo_parameter_space_recovery"]["normalized_frobenius_error"] for r in runs]
    coll_frob = [r["collusion"]["colluded_parameter_space_recovery"]["normalized_frobenius_error"] for r in runs]
    solo_func = [r["collusion"]["solo_functional_fine_macro_f1"] for r in runs]
    coll_func = [r["collusion"]["colluded_functional_fine_macro_f1"] for r in runs]

    cm, cs = mean_std(solo_cos)
    fm, fs = mean_std(solo_frob)
    um, us = mean_std(solo_func)
    rows.append({"scenario": "collusion_solo_half", "reveal_fraction": runs[0]["config"]["collusion_reveal_fraction_each"],
                 "n_seeds": len(runs), "cosine_similarity_mean": cm, "cosine_similarity_std": cs,
                 "normalized_frobenius_error_mean": fm, "normalized_frobenius_error_std": fs,
                 "functional_fine_macro_f1_mean": um, "functional_fine_macro_f1_std": us})

    cm, cs = mean_std(coll_cos)
    fm, fs = mean_std(coll_frob)
    um, us = mean_std(coll_func)
    rows.append({"scenario": "collusion_pooled", "reveal_fraction": round(statistics.mean(pooled_fracs), 3),
                 "n_seeds": len(runs), "cosine_similarity_mean": cm, "cosine_similarity_std": cs,
                 "normalized_frobenius_error_mean": fm, "normalized_frobenius_error_std": fs,
                 "functional_fine_macro_f1_mean": um, "functional_fine_macro_f1_std": us})

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 3 P1-7 genuine parameter-space adapter recovery — SYNTHETIC TIER",
        "",
        "Generated by scripts/make_phase3_adapter_recovery_table.py from "
        "experiments/phase3_adapter_recovery_synthetic/*.json — do not hand-edit.",
        "Attacker starts from a PARTIAL, genuinely-leaked copy of the true adapter.up matrix's own entries "
        "(NOT an AES-GCM break — medgate/attacks/adapter_recovery.py) and completes it via low-rank matrix "
        "completion; cosine_similarity/normalized_frobenius_error are PARAMETER-space recovery, "
        "functional_fine_macro_f1 plugs the completed adapter into the model and evaluates the fine task.",
        "",
        "| scenario | reveal fraction | seeds | cosine sim | frob. error | functional fine-F1 |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['scenario']} | {row['reveal_fraction']:.2f} | {row['n_seeds']} "
            f"| {row['cosine_similarity_mean']:.3f} ± {row['cosine_similarity_std']:.3f} "
            f"| {row['normalized_frobenius_error_mean']:.3f} ± {row['normalized_frobenius_error_std']:.3f} "
            f"| {row['functional_fine_macro_f1_mean']:.3f} ± {row['functional_fine_macro_f1_std']:.3f} |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_CSV} and {OUT_MD} from {len(runs)} seeds, {len(rows)} rows")


if __name__ == "__main__":
    main()
