#!/usr/bin/env python3
"""Generate paper/tables/phase4_concealment_sweep.{csv,md} from
experiments/phase4_concealment_sweep/sweep.json (P0-B requirement, repair
pass 4). Never hand-typed.

Usage: PYTHONPATH=. python scripts/make_phase4_concealment_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_PATH = Path("experiments/phase4_concealment_sweep/sweep.json")
TABLES = Path("paper/tables")


def main():
    if not IN_PATH.exists():
        raise SystemExit(f"{IN_PATH} not found — run scripts/run_phase4_concealment_sweep.py first")
    data = json.loads(IN_PATH.read_text())
    rows_by_key = {}
    for r in data["rows"]:
        key = (r["mask_scale"], r["attacker"])
        rows_by_key.setdefault(key, []).append(r["masked_case_attack_auc"])

    rows = []
    for (mask_scale, attacker), aucs in sorted(rows_by_key.items()):
        m = statistics.mean(aucs)
        s = statistics.stdev(aucs) if len(aucs) > 1 else 0.0
        rows.append({"mask_scale": mask_scale, "attacker": attacker, "n_seeds": len(aucs),
                     "masked_case_attack_auc_mean": m, "masked_case_attack_auc_std": s})

    out_csv = TABLES / "phase4_concealment_sweep.csv"
    with open(out_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 4 P0-B mask-scale / attacker concealment sweep",
        "", "Generated by scripts/make_phase4_concealment_table.py -- do not hand-edit.",
        "unmasked_control_attack_auc was ~1.0 in every row (omitted) -- the two synthetic distributions",
        "are trivially separable before masking, confirming the masked-case AUC reflects the mask's effect.",
        "", "| mask scale | attacker | seeds | masked-case attack AUC |", "|---|---|---|---|",
    ]
    for row in rows:
        lines.append(f"| {row['mask_scale']:.2f} | {row['attacker']} | {row['n_seeds']} "
                      f"| {row['masked_case_attack_auc_mean']:.3f} ± {row['masked_case_attack_auc_std']:.3f} |")
    (TABLES / "phase4_concealment_sweep.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {out_csv} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
