#!/usr/bin/env python3
"""Generate paper/tables/phase5_unlearning_synthetic.{csv,md} (primary
results, symmetric_auc-based) and
paper/tables/phase5_unlearning_confounded_appendix.{csv,md} (the ORIGINAL
confounded class-scenario metric, preserved only as a documented negative
example per the project brief, never as evidence) from
experiments/phase5_synthetic/*.json. Never hand-typed.

Usage: PYTHONPATH=. python scripts/make_phase5_table.py
"""
import csv
import json
import statistics
from pathlib import Path

IN_DIR = Path("experiments/phase5_synthetic")
OUT_CSV = Path("paper/tables/phase5_unlearning_synthetic.csv")
OUT_MD = Path("paper/tables/phase5_unlearning_synthetic.md")
CONFOUNDED_CSV = Path("paper/tables/phase5_unlearning_confounded_appendix.csv")
CONFOUNDED_MD = Path("paper/tables/phase5_unlearning_confounded_appendix.md")


def mean_std(vals):
    return statistics.mean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def main():
    runs = [json.loads(p.read_text()) for p in sorted(IN_DIR.glob("*.json"))]
    if not runs:
        raise SystemExit(f"no run JSON files under {IN_DIR} — run scripts/run_phase5_synthetic.py first")

    groups, confounded_groups = {}, {}
    for run in runs:
        for method, m in run["methods"].items():
            key = (run["scenario"], method)
            groups.setdefault(key, {"retained_f1": [], "gap": [], "sym_auc": [], "advantage": [], "raw_auc": []})
            groups[key]["retained_f1"].append(m["retained_fine_macro_f1"])
            groups[key]["gap"].append(m["gap_to_gold_standard"])
            groups[key]["sym_auc"].append(m["forgetting_symmetric_auc"])
            groups[key]["advantage"].append(m["forgetting_attack_advantage"])
            groups[key]["raw_auc"].append(m["forgetting_raw_auc_diagnostic_only"])
            confounded_key = "confounded_cross_class_forgetting_symmetric_auc_DO_NOT_USE_AS_EVIDENCE"
            if confounded_key in m:
                confounded_groups.setdefault(method, []).append(m[confounded_key])

    rows = []
    for (scenario, method), vals in sorted(groups.items()):
        f1_m, f1_s = mean_std(vals["retained_f1"])
        gap_m, gap_s = mean_std(vals["gap"])
        sym_m, sym_s = mean_std(vals["sym_auc"])
        adv_m, adv_s = mean_std(vals["advantage"])
        raw_m, raw_s = mean_std(vals["raw_auc"])
        rows.append({
            "scenario": scenario, "method": method, "n_seeds": len(vals["retained_f1"]),
            "retained_fine_macro_f1_mean": f1_m, "retained_fine_macro_f1_std": f1_s,
            "gap_to_gold_standard_mean": gap_m, "gap_to_gold_standard_std": gap_s,
            "forgetting_symmetric_auc_mean": sym_m, "forgetting_symmetric_auc_std": sym_s,
            "forgetting_attack_advantage_mean": adv_m, "forgetting_attack_advantage_std": adv_s,
            "forgetting_raw_auc_diagnostic_mean": raw_m, "forgetting_raw_auc_diagnostic_std": raw_s,
        })

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    lines = [
        "# Phase 5 revocation and unlearning — SYNTHETIC TIER (pipeline validation, not a scientific result)",
        "",
        "Real Fed-ISIC2019 results are BLOCKED-LICENSE; see docs/execution_plan.md.",
        "Generated by scripts/make_phase5_table.py from experiments/phase5_synthetic/*.json — do not hand-edit.",
        "PRIMARY forgetting score: forgetting_symmetric_auc = max(AUC, 1-AUC), 0.5=no membership signal (good forgetting),",
        "1.0=fully distinguishable in either direction. Raw AUC is a diagnostic field only -- it is direction-sensitive",
        "(AUC=0.0 is JUST AS distinguishable as AUC=1.0, only the score direction differs) and must never be read as",
        "'closer to 0 is safe' -- see medgate/attacks/membership_inference.py and tests/test_unlearning_metrics.py.",
        "The `class` scenario's primary score now compares removed data against a WITHIN-CLASS never-trained control",
        "pool (medgate.data.synthetic.make_never_trained_class_pool), not retained-test data of other classes -- the",
        "original cross-class-confounded metric is preserved separately in phase5_unlearning_confounded_appendix.md",
        "as a documented negative example, never as evidence.",
        "",
        "| scenario | method | n_seeds | retained fine macro-F1 | gap to gold standard | forgetting SymmetricAUC | attack advantage | raw AUC (diagnostic) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['scenario']} | {row['method']} | {row['n_seeds']} "
            f"| {row['retained_fine_macro_f1_mean']:.3f} ± {row['retained_fine_macro_f1_std']:.3f} "
            f"| {row['gap_to_gold_standard_mean']:+.3f} ± {row['gap_to_gold_standard_std']:.3f} "
            f"| {row['forgetting_symmetric_auc_mean']:.3f} ± {row['forgetting_symmetric_auc_std']:.3f} "
            f"| {row['forgetting_attack_advantage_mean']:.3f} ± {row['forgetting_attack_advantage_std']:.3f} "
            f"| {row['forgetting_raw_auc_diagnostic_mean']:.3f} ± {row['forgetting_raw_auc_diagnostic_std']:.3f} |"
        )
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n")

    if confounded_groups:
        crows = []
        for method, vals in sorted(confounded_groups.items()):
            m, s = mean_std(vals)
            crows.append({"method": method, "n_seeds": len(vals), "confounded_symmetric_auc_mean": m, "confounded_symmetric_auc_std": s})
        with open(CONFOUNDED_CSV, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(crows[0].keys()))
            w.writeheader()
            w.writerows(crows)
        clines = [
            "# Appendix: the ORIGINAL confounded class-scenario forgetting metric — DOCUMENTED NEGATIVE EXAMPLE, NOT EVIDENCE",
            "",
            "Preserved per the project brief ('Retain the original confounded result only as a documented negative example",
            "in an appendix, not as evidence.'). This compares removed class-level data against retained TEST DATA OF",
            "OTHER CLASSES -- confounded because any class-level loss asymmetry that exists even in an UNTRAINED model",
            "biases this number regardless of real memorization (e.g. checkpoint_rollback, never trained on the",
            "post-removal data at all, still showed ~0.99 here in an earlier run). Do not cite this table as evidence of",
            "forgetting quality; see phase5_unlearning_synthetic.md for the corrected within-class primary metric.",
            "",
            "| method | n_seeds | confounded symmetric AUC |",
            "|---|---|---|",
        ]
        for row in crows:
            clines.append(f"| {row['method']} | {row['n_seeds']} | {row['confounded_symmetric_auc_mean']:.3f} ± {row['confounded_symmetric_auc_std']:.3f} |")
        CONFOUNDED_MD.parent.mkdir(parents=True, exist_ok=True)
        CONFOUNDED_MD.write_text("\n".join(clines) + "\n")

    print(f"wrote {OUT_CSV}, {OUT_MD}"
          + (f", {CONFOUNDED_CSV}, {CONFOUNDED_MD}" if confounded_groups else "")
          + f" from {len(runs)} run files, {len(rows)} scenario/method combinations")


if __name__ == "__main__":
    main()
